const id = location.pathname.split("/").pop(), root = document.querySelector("#policy"), crumb = document.querySelector("#policy-crumb"), form = document.querySelector("#version-upload"), message = document.querySelector("#message");
const el = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
const label = (state) => ({ ready: "Ready to search", pending: "Processing", processing: "Processing", failed: "Needs attention" }[state] || state || "Processing");
const badge = (state) => el("span", `pol-status is-${state || "pending"}`, label(state));
async function json(response) { return response.json().catch(() => ({})); }
function setMessage(text, failed = false) { message.textContent = text; message.classList.toggle("is-error", failed); }
function versionCard(version, currentId) {
  const article = el("article", `pol-version${version.policy_version_id === currentId ? " is-current" : ""}`), head = el("div", "pol-version-head");
  head.append(el("h2", "", `Version ${version.version_number}${version.policy_version_id === currentId ? " · current" : ""}`), badge(version.status)); article.append(head);
  if (version.error_message) article.append(el("p", "pol-version-note is-error", version.error_message)); else if (version.status !== "ready") article.append(el("p", "pol-version-note", "This upload is being prepared locally. The current ready version remains searchable."));
  const actions = el("div", "pol-version-actions"), download = el("a", "pol-download", `Download original · ${version.original_filename}`); download.href = `/api/policies/${encodeURIComponent(id)}/versions/${encodeURIComponent(version.policy_version_id)}/download`; actions.append(download);
  if (version.status === "failed") { const retry = el("button", "btn btn-secondary pol-retry", "Retry processing"); retry.type = "button"; retry.onclick = async () => { retry.disabled = true; try { const response = await fetch(`/api/policies/${encodeURIComponent(id)}/versions/${encodeURIComponent(version.policy_version_id)}/retry`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }), data = await json(response); if (!response.ok) throw new Error(data.error?.message || "Could not retry processing."); setMessage("Retry accepted. Convene is processing the document locally."); await refresh(); } catch (cause) { setMessage(cause.message, true); } finally { retry.disabled = false; } }; actions.append(retry); }
  article.append(actions); if (version.extracted_text) article.append(el("pre", "pol-text", version.extracted_text)); return article;
}
async function refresh() { try { const response = await fetch(`/api/policies/${encodeURIComponent(id)}`), data = await json(response); if (!response.ok) throw new Error(data.error?.message || "Could not load this policy."); crumb.textContent = data.policy.title || "Policy"; const head = el("div", "pol-detail-head"); head.append(el("p", "pol-eyebrow", "Knowledge base"), el("h1", "", data.policy.title || "Untitled policy"), el("p", "", "Versions are retained locally. Only a successfully indexed version is used for policy answers.")); const cards = el("div", "pol-version-list"); for (const version of data.versions || []) cards.append(versionCard(version, data.policy.current_version_id)); if (!cards.childElementCount) cards.append(el("p", "pol-version-note", "No uploaded versions yet.")); root.replaceChildren(head, cards); } catch (cause) { root.replaceChildren(el("p", "hx-error", cause.message)); } }
form.addEventListener("submit", async (event) => { event.preventDefault(); const submit = form.querySelector("button[type=submit]"); submit.disabled = true; setMessage("Uploading…"); try { const response = await fetch(`/api/policies/${encodeURIComponent(id)}/versions`, { method: "POST", body: new FormData(form) }), data = await json(response); if (!response.ok) throw new Error(data.error?.message || "Upload failed."); form.reset(); setMessage("Upload accepted. Convene is processing it locally in the background."); await refresh(); } catch (cause) { setMessage(cause.message, true); } finally { submit.disabled = false; } }); refresh();
